#!/bin/bash
echo Saving container logs...
touch logs
docker logs senko >> logs

docker build -t mtsev/senko .

echo Delete old container...
docker rm -f senko

echo Run new container...
docker run -d \
	--name senko \
	--restart=always \
	--network host \
	mtsev/senko
